INSERT INTO CURRENCY_EXCHANGE VALUES(1000,75,'','USD','INR');
INSERT INTO CURRENCY_EXCHANGE VALUES(1001,85,'','UKP','INR');
INSERT INTO CURRENCY_EXCHANGE VALUES(1002,120,'','EUR','INR');
INSERT INTO CURRENCY_EXCHANGE VALUES(1003,50,'','CAN','INR');
INSERT INTO CURRENCY_EXCHANGE VALUES(1004,25,'','AUS','INR');